services:

  _defaults:
    public: false
    autowire: true

  OxidAcademy\ProductPromotionBanner\Service\:
    resource: 'src/Service/*'
    public: true
  
  OxidAcademy\ProductPromotionBanner\Subscriber\AfterModelUpdate:
    tags: [ 'kernel.event_subscriber' ]
